### ISSUE TITLE
Seems we have a new problem with form.html

### ISSUE THREAD

**Issue by icexuick** [spring/upq#83]
When uploading new (map) file to https://springfiles.springrts.com/upload/ we now get this:

```
Traceback (most recent call last):
  File "/home/springfiles/upq/www/upload/index.py", line 104, in <module>
    ShowForm({"messages": "<pre>" + html.escape(msgs) + "</pre>"})
  File "/home/springfiles/upq/www/upload/index.py", line 13, in ShowForm
    with open("form.html", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'form.html'
```

**Comment by abma** [comment]
try again please. i guess your uploaded file is broken and triggers some error which makes it fail like this.

the change adds some wrapper which should correctly cwd after parsing...
